spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/webhookhub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=NewStrongPassword123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2849887714fc04d2757d598b2c45b7dc735f4a0b2d6a504b7e80a08e1a17f694e92a2a0eb732a39a2fbaf0b5401314950
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_mail@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
